version: '3'

volumes:
  postgres:

services:
  postgres:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=my-gallery
      - POSTGRES_DB=my-gallery
      - POSTGRES_PASSWORD=my-gallery
    volumes:
      - postgres
